---
title: "Replicate Figures"
---

Summary: Code to replicate all figures and tables in "Berkeley Unified Numident Mortality Database: Public Administrative Records for Individual-Level Mortality Research" 

To replicate, move the 

## Setup 

Library packages and source functions 

```{r}
library(tidyverse)
library(data.table)
library(memisc)
library(here)
library(HMDHFDplus)
library(gridExtra)
library(ggpubr)
library(cowplot)

## source functions 
source(here("code/00_helper_functions.R"))

## Read in BUNMD file
bunmd <- fread(here("data/bunmd_v2.csv"))
hmd <- fread(here("data/bunmd_v2.csv"))
```

## Compare BUNMD and HMD Death Coverage 

```{r}
## Get HMD deaths from website
hmd <- hmd %>%
  mutate(linking_key = paste(Year, Age, sep = "_" ))

## Tabulate deaths in BUNMD for 65+
bunmd.deaths.tabulated <- bunmd %>% 
  filter(death_age >= 65) %>% 
  group_by(Year = dyear) %>% 
  filter(Year > 1960) %>% 
  summarize(deaths = n()) %>% 
  mutate(source = "BUNMD")

## Tabulate deaths in BUNMD for 65+
bunmd.deaths.tabulated_complete <- bunmd %>% 
  filter(!is.na(ccweight)) %>% 
  filter(death_age >= 65) %>% 
  group_by(Year = dyear) %>% 
  filter(Year > 1960) %>% 
  summarize(deaths = n()) %>% 
  mutate(source = "BUNMD Complete Case")

## Tabulate deaths in HMD for 65+ 
hmd.deaths.tabulated <- hmd_deaths %>%
  filter(Age >= 65) %>% 
  group_by(Year) %>% 
  filter(Year > 1960) %>% 
  summarize(deaths = sum(Total)) %>% 
  mutate(source = "Human Mortality Database")

## Combine into one data frame 
data.for.plot <- bunmd.deaths.tabulated %>% 
  bind_rows(hmd.deaths.tabulated) %>% 
  bind_rows(bunmd.deaths.tabulated_complete) %>% 
  filter(Year > 1970 & Year < 2006)

## Create death coverage plot
bunmd_coverage <- ggplot(data.for.plot) + 
  geom_line((aes(x = Year, y = deaths, linetype=source))) + 
  labs(x = "Year", 
       y = "Count") + 
  scale_y_continuous(labels = scales::comma) + 
  scale_x_continuous(breaks = scales::pretty_breaks(n=10)) + 
  theme_cowplot() + 
  theme(legend.position="bottom", legend.title = element_blank()) 

ggsave(plot = bunmd_coverage, filename = here("figs/bunmd_coverage.pdf"), width = 10, height = 6)
```

## Lexis plots  

```{r}
########################################################
# Create BUNMD Lexis Plot
########################################################

## Get HMD deaths
hmd_deaths <-  readHMDweb(CNTRY = "USA", item = "Deaths_1x1", username ="caseybreen@berkeley.edu", password = "censoc") %>% mutate(linking_key = paste(Year, Age, sep = "_" ))

## Tabulate BUNMD 
bunmd.tabulation <- bunmd %>% 
  filter(death_age %in% 0:100) %>% 
  group_by(Year = dyear, Age = death_age) %>% 
  filter(Year %in% c(1940:2010)) %>% 
  summarize(deaths = n()) 

## HMD tabulation
hmd.tabulation <- hmd_deaths %>% 
  filter(Age %in% 0:100) %>% 
  group_by(Year, Age) %>% 
  filter(Year %in% c(1940:2010)) %>% 
  summarize(deaths = sum(Total)) %>% 
  mutate(source = "HMD")

## Prep data for Lexis Function
lexis.data <- bunmd.tabulation %>% 
  inner_join(hmd.tabulation, by = c("Year", "Age" )) %>%
  mutate(coverage = deaths.x/deaths.y)

## Call Lexis Function
lexis_coverage <- lexis(data = lexis.data, year_begin = 1940, age_begin = 0, fill_column = coverage, breaks = c(0, 0.25, .5, .75, .9, .95, 5),
                        labels = c( "0 to 25%",
                                    "25% to 50%",
                                    "50% to 75%",
                                    "75% to 90%",
                                    "90% to 95%",
                                    ">95% Death Coverage")) +
  labs(
    x = "",
    y = "Average Rating (0-10)",
    title = "Coverage",
    subtitle = ""
  )

## Prep data for Lexis Function
lexis.data.filter <- lexis.data %>% 
  filter(Year > 1985 & Age > 65)

## Call Lexis Function
lexis_coverage_all <- lexis(data = lexis.data.filter, year_begin = 1985, age_begin = 65, fill_column = coverage, breaks = c(0, 0.25, .5, .75, .9, .95, 5),
                            labels = c( "0%to 25%",
                                        "25% to 50%",
                                        "50% to 75%",
                                        "75% to 90%",
                                        "90% to 95%",
                                        ">95% Death Coverage")) +
  labs(
    x = "",
    y = "Average Rating (0-10)",
    title = "High Coverage Subsample",
    subtitle = ""
  )

bunmd.lexis <- ggarrange(lexis_coverage, lexis_coverage_all, common.legend = T, legend="bottom")

bunmd.lexis <- annotate_figure(bunmd.lexis,
                               top = text_grob("BUNMD Death Record Coverage \n",
                                               face = "bold", size = 30))
```


## Cuba Example 

```{r}
## restrict to rows with complete birthplace and race
bunmd <- bunmd %>% 
  filter(!is.na(ccweight)) %>% 
  as.data.table

## bunmd 
bunmd <- bunmd %>% 
  mutate(country = bpl_string)

dt[bpl ==  15000, country := "Canada"]
dt[bpl ==  20000, country := "Mexico"]
dt[bpl ==  25000, country := "Cuba"]
dt[bpl ==  26030, country := "Jamaica"]
dt[bpl ==  41000, country := "England"]
dt[bpl ==  41400, country := "Ireland"]
dt[bpl ==  43300, country := "Greece"]
dt[bpl ==  43400, country := "Italy"]
dt[bpl ==  43600, country := "Portugal"]
dt[bpl ==  45010, country := "Austria"]
dt[bpl ==  45200, country := "Czechoslovakia"]
dt[bpl ==  45310, country := "Germany"]
dt[bpl ==  45500, country := "Poland"]
dt[bpl ==  45700, country := "Yugoslavia"]
dt[bpl ==  46500, country := "Russia"]
dt[bpl ==  50000, country := "China"]
dt[bpl ==  50220, country := "Korea"]
dt[bpl ==  50100, country := "Japan"]
dt[bpl ==  51500, country := "Philippines"]
dt[bpl ==  54100, country := "Syria"]
dt[bpl < 1300,    country := "USA"]

## prepare variables for regression
dt[, Byear := as.factor(byear)]
dt[, Byear := relevel(Byear, ref = "1910")]

## recode race
dt[race_first == 1, Race := "White"]
dt[race_first == 2, Race := "Black"]
dt[race_first == 3, Race := "Other"]
dt[race_first == 4, Race := "Asian"]
dt[race_first == 5, Race := "Hispanic"]
dt[race_first == 6, Race := "Native"]
dt[, Race := relevel(as.factor(Race), ref = "White")] ## capital "W"?

## restrict to years with high coverage 
## restrict to Cuba
my.dt.3 <- dt[country %in% c("Cuba") &
              byear %in% 1900:1920 &
              dyear %in% 1988:2005 &
              age_first_application < 65]

## For this analysis, we focus on the original answer that people gave to the race question. Most of these responses were prior to 1980, 
## when there were only 3 categories ("White", "Black", and "Other"). (A possible extension of this initial analysis would be to consider 
## responses to post-1980 race classification, which included "Hispanic", "Asian", and "Native American".
## However, analysis of the post-1980 classification is complicated by the fact that most of these respondents were filling out the form for a 2nd time

## you can only be White, Black, or Other before 1980
my.dt.3[race_first == 1 & race_first_cyear < 1980, Race_pre_1980 := "White"]
my.dt.3[race_first == 2 & race_first_cyear < 1980, Race_pre_1980 := "Black"]
my.dt.3[race_first == 3 & race_first_cyear < 1980, Race_pre_1980 := "Other"]

## Set reference groups
my.dt.3[, Race_pre_1980 := relevel(factor(Race_pre_1980), ref = "White")]

## Run regression seperately for men and women
m.cuba.m.pre_1980 <-  lm(death_age ~ Race_pre_1980 +  Byear,
                      data = my.dt.3,
                      subset = sex == 1,
                      weight = cweight)

m.cuba.f.pre_1980 <- update(m.cuba.m.pre_1980,
                   subset = sex == 2)

mtable(m.cuba.m.pre_1980, m.cuba.f.pre_1980)

## crosstabs
my.dt.3[, table(Race_pre_1980, sex)]

## both sexes combined -- table for paper
m.cuba.mf.pre_1980 <-  lm(death_age ~ Race_pre_1980 +  Byear + as.factor(sex),
                      data = my.dt.3,
                      weight = cweight)

## crosstabs
mtable(m.cuba.mf.pre_1980)

## Create table for paper
## library(stargazer)
## stargazer(m.cuba.mf.pre_1980, single.row = TRUE)
```


```{r}
#####################################################################
## An example comparing foreign born and native longevity Using BUNMD
##################################################################### 

## 1) read in "complete" sample
## 2) create analysis variables
## 3) example 1: 1 cohort only
## 4) example 2: a bunch of cohorts
## 5) example 3: cubans by race
## 6) note on regression coefficients

dt <- bunmd %>% 
    filter(!is.na(ccweight)) %>% 
    as.data.table()

## 2) create analysis variables

## code countries with a lot of immigrants
dt[, country := vector(mode = "character", length = nrow(dt))]
dt[bpl ==  15000, country := "Canada"]
dt[bpl ==  20000, country := "Mexico"]
dt[bpl ==  25000, country := "Cuba"]
dt[bpl ==  26030, country := "Jamaica"]
dt[bpl ==  41000, country := "England"]
dt[bpl ==  41400, country := "Ireland"]
dt[bpl ==  43300, country := "Greece"]
dt[bpl ==  43400, country := "Italy"]
dt[bpl ==  43600, country := "Portugal"]
dt[bpl ==  45010, country := "Austria"]
dt[bpl ==  45200, country := "Czechoslovakia"]
dt[bpl ==  45310, country := "Germany"]
dt[bpl ==  45500, country := "Poland"]
dt[bpl ==  45700, country := "Yugoslavia"]
dt[bpl ==  46500, country := "Russia"]
dt[bpl ==  50000, country := "China"]
## dt[bpl ==  50220, country := "Korea"]
## dt[bpl ==  50100, country := "Japan"]
dt[bpl ==  51500, country := "Philippines"]
## dt[bpl ==  54100, country := "Syria"]
dt[bpl < 1300,    country := "USA"]

## Set USA as reference group
dt[, country := relevel(factor(country), ref = "USA")]

## prepare variables for regression
dt[, Byear := as.factor(byear)]
dt[, Byear := relevel(Byear, ref = "1910")]

## 3) example 1: 1 cohort only
#####################################
## example 1: Cohort born in 1915  ##
#####################################

tab <- table(dt[byear == 1915]$death_age)

head(tab)
##    72    73    74    75    76    77
## 20259 42086 44279 45199 47473 50175
tail(tab)
##    85    86    87    88    89    90
## 62710 62744 60327 59182 54581 23996

## Notice: the end-ages have only half the deaths, because of Lexis
## triangles.

my.dt.1 <- dt[byear == 1915 &
            death_age %in% 73:89 & ## we omit first and last ages
            age_first_application < 65] ## we restrict to those in the US before age 65
##
## male
m.immig.male <- lm(death_age ~ country,
                   data = my.dt.1,
                   weight = ccweight,
                   subset = sex  == 1)
## female
m.immig.female <- update(m.immig.male,
                         subset = sex == 2)
##
## figure
##  pdf("birth_place_fig1.pdf", width = 6, height = 6)

par(mfrow = c(2,1),
    mar = c(5, 4, 4, 2) +.1)
color_coef_plot.fun(m.immig.female, "country", labeled_color.vec,
                    xlim = c(-1, 2))
text(0, 16.5, "Natives", pos = 2, col = "darkgrey", cex = .6)
title("Foreign-born female ages of death, cohort 1915")
color_coef_plot.fun(m.immig.male, "country", labeled_color.vec,
                    xlim = c(-1, 2))
title("Foreign-born male ages of death, cohort 1915a")
text(0, 16.5, "Natives", pos = 2, col = "darkgrey", cex = .)
## dev.off()
## system("open birth_place_fig1.pdf")

## sample size table

tab.1 <- my.dt.1[, round(xtabs(cweight ~ country + sex))]
tab.2 <- my.dt.2[, round(xtabs(cweight ~ country + sex))]
format(cbind(tab.1, tab.2), big.mark = ",")

#########################################
## example 2: Cohorts born in 1910-19 (Figure in paper)  ##
#########################################
my.dt.2 <- dt[byear %in% 1910:1919 &
            dyear %in% 1988:2005 &
            age_first_application < 65]
## male
m.immig.male.2 <- lm(death_age ~ country +  Byear,
                   data = my.dt.2,
                   weight = ccweight,
                   subset = sex  == 1)
## female
m.immig.female.2 <- update(m.immig.male.2,
                         subset = sex == 2)

## figure
par(mfrow = c(2,1),
    mar = c(5, 4, 4, 2) +.1)
color_coef_plot.fun(m.immig.female.2, "country", labeled_color.vec,
                    xlim = c(-1, 2))
text(0, 16.5, "Natives", pos = 2, col = "darkgrey", cex = .6)
title("Foreign-born female ages of death, cohorts 1910-19")
color_coef_plot.fun(m.immig.male.2, "country", labeled_color.vec,
                    xlim = c(-1, 2))
title("Foreign-born male ages of death, cohorts 1910-19")
text(0, 16.5, "Natives", pos = 2, col = "darkgrey", cex = .6)

## sample size table
tab.1 <- my.dt.1[, round(xtabs(ccweight ~ country + sex))]
tab.2 <- my.dt.2[, round(xtabs(ccweight ~ country + sex))]
format(cbind(tab.1, tab.2), big.mark = ",")

```



