---
title: "Mortality Estimation: Replicate Figures"
author: Casey Breen
---

Summary: Code to replicate figures and tables in "Berkeley Unified Numident Mortality Database: Public Administrative Records for Individual-Level Mortality Research" for "Mortality Estimation" section. 

## Setup 

Library packages and source functions 

```{r}
## Library packages 
library(tidyverse)
library(data.table)
library(memisc)
library(here)
library(HMDHFDplus)
library(gridExtra)
library(ggpubr)
library(cowplot)
library(gt)
library(fixest)
library(stargazer)
library(choroplethrZip)
library(choroplethr)
library(sf)
library(broom)
library(lubridate)

## source functions 
source(here("code/helper_functions.R"))
```

## Figure 3  — Distribution of Age of Death Plot 

Two-panel Plot highlighting effect of truncation 

```{r}
## create mortality distribution (untruncated)
trunc_diff <-  tibble(
  pop1  = dgompertz.M(x = 65:110, b = 0.09, M = 80.8),
  pop2  = dgompertz.M(x = 65:110, b = 0.09, M = 85),
  age = 65:110)

## calculate average age of death 
trunc_diff_means <- trunc_diff %>% 
  summarize(pop1_mean = sum(pop1*age)/sum(pop1),
            pop2_mean = sum(pop2*age)/sum(pop2))

## plot untruncated mortality distributions 
truncated_means_plot1 <- trunc_diff %>% 
  ggplot() + 
  geom_line(aes(x = age, y = pop1*100000), color = "red") + 
  geom_line(aes(x = age, y = pop2*100000), color = "blue") + 
  theme_cowplot(rel_large = .75) + 
  labs(x = "Age",
       y = "Deaths",
       title = "Untruncated") + 
  geom_vline(xintercept = trunc_diff_means$pop1_mean, color = "red", linetype = "dashed") + 
  geom_vline(xintercept = trunc_diff_means$pop2_mean, color = "blue", linetype = "dashed") + 
  xlim(65, 110) + 
  ylim(0, 0.04*100000) + 
  annotate("text", x=trunc_diff_means$pop1_mean-1.2, y = 130, 
           label = round(trunc_diff_means$pop1_mean, 1), color = "red") + 
  annotate("text", x=trunc_diff_means$pop2_mean+1.2, y = 130, 
           label = round(trunc_diff_means$pop2_mean, 1), color = "blue") + 
  annotate("text", x = 102.8, y = 3500, label = paste0("Difference = ", round(trunc_diff_means$pop2_mean - trunc_diff_means$pop1_mean, 1), " years"))

## now truncate mortality distribution 
trunc_diff_truncated <- trunc_diff %>% 
  filter(age %in% c(78:95))

## calculate average age of death 
trunc_diff_means_truncated <- trunc_diff_truncated %>% 
  summarize(pop1_mean = sum(pop1*age)/sum(pop1),
            pop2_mean = sum(pop2*age)/sum(pop2))

## plot untruncated mortality distribution 
truncated_means_plot2 <- trunc_diff_truncated %>% 
  ggplot() + 
  geom_line(aes(x = age, y = pop1*100000, color = "Native-born")) + 
  geom_line(aes(x = age, y = pop2*100000,  color = "Foreign-born")) + 
  theme_cowplot(rel_large = .75) + 
  labs(x = "Age",
       y = "Deaths",
      title = "Doubly Truncated") + 
  geom_vline(xintercept = trunc_diff_means_truncated$pop1_mean, color = "red", linetype = "dashed") + 
  geom_vline(xintercept = trunc_diff_means_truncated$pop2_mean, color = "blue", linetype = "dashed") + 
  geom_vline(xintercept = 78, color = "grey") + 
  geom_vline(xintercept = 95, color = "grey") + 
  xlim(65, 110) +
  ylim(0, 0.04*100000) + 
  annotate("text", x = trunc_diff_means_truncated$pop1_mean-2, y = 0.013*100000, 
           label = round(trunc_diff_means_truncated$pop1_mean, 1), color = "red") + 
  annotate("text", x = trunc_diff_means_truncated$pop2_mean+2, y = 0.013*100000, 
           label = round(trunc_diff_means_truncated$pop2_mean, 1), color = "blue") + 
  annotate("text", x = 102.8, y = 3500, 
           label = paste0("Difference = ", round(trunc_diff_means_truncated$pop2_mean - trunc_diff_means_truncated$pop1_mean, 1), " years")) + 
  scale_color_manual(name = "", values = c("Native-born" = "red", "Foreign-born" = "blue")) + 
  theme(legend.position = "bottom")

## truncated means 
truncated_means <- cowplot::plot_grid(truncated_means_plot1, truncated_means_plot2, nrow = 2, labels = "auto")

ggsave(plot = truncated_means, filename = here("figs/03_truncated_means.pdf"), width = 7, height = 6.1)
```



