---
title: "R Notebook"
output: html_notebook
---

Library packages
```{r}
library(tidyverse)
```


Read in a .csv with three variables: 
- numident file
- variable 
- percent coverage

```{r}
coverage <- read_csv("percent_na_coverage.csv") %>% 
  mutate(all.missing = case_when(
    value <= 0.01 ~ "yes",
    value > 0.01 ~ "no"
  ))
```

```{r}
death_completeness <- coverage %>% 
  filter(numident_file == "deaths") %>% 
  filter(!str_detect(name, "FILLER")) %>% 
ggplot() + 
  geom_point(aes(x = reorder(name, value), y = value, shape = all.missing), size = 3, show.legend = FALSE) + 
  geom_segment( aes(x = name, xend = name, y=0, yend=value), color="black") +
  theme_classic() +
  geom_segment(aes(
    x = name,
    xend = name, 
    y = min(value),
    yend = max(value)
  ),
  linetype = "dashed",
  size = 0.1
  ) + # Draw dashed lines
  coord_flip() + 
  scale_shape_manual(values = c(16, 1)) +
  labs(title = "Numident Death Files Variable Completeness",
       x = "Variable",
       y = "Completeness %")

ggsave(plot = death_completeness, filename = "/Users/casey/Documents/censoc/numident_paper/illustrations/death_coverage.png", height = 11, width = 8.5)
```

```{r}
app_completeness <- coverage %>% 
  filter(numident_file == "apps") %>% 
  filter(!str_detect(name, "FILLER")) %>% 
  #filter(value > 0) %>% 
ggplot() + 
  geom_point(aes(x = reorder(name, value), y = value, shape = all.missing), size = 3, show.legend = FALSE) + 
  geom_segment( aes(x = name, xend = name, y=0, yend=value), color="black") +
  theme_classic() +
  geom_segment(aes(
    x = name,
    xend = name, 
    y = min(value),
    yend = max(value)
  ),
  linetype = "dashed",
  size = 0.1
  ) + # Draw dashed lines
  coord_flip() + 
  scale_shape_manual(values = c(16, 1)) +
  labs(title = "Numident Application Files Variable Completeness",
       x = "Variable",
       y = "Completeness %") +
  ylim(0, 100)

ggsave(plot = app_completeness, filename = "/Users/casey/Documents/censoc/numident_paper/illustrations/application_coverage.png", height = 11, width = 8.5)
```

```{r}
claim_coverage <- coverage %>% 
  filter(numident_file == "claims") %>% 
  filter(!str_detect(name, "FILLER")) %>% 
 # filter(value > 1) %>% 
ggplot() + 
  geom_point(aes(x = reorder(name, value), y = value, shape = all.missing), size = 3, show.legend = FALSE) + 
  geom_segment( aes(x = name, xend = name, y=0, yend=value), color="black") +
  theme_classic() +
  geom_segment(aes(
    x = name,
    xend = name, 
    y = min(value),
    yend = max(value)
  ),
  linetype = "dashed",
  size = 0.1
  ) + # Draw dashed lines
  coord_flip() + 
  scale_shape_manual(values = c(16, 1)) +
  labs(title = "Numident Claim Files Variable Completeness",
       x = "Variable",
       y = "Completeness %") + 
  guides(fill=FALSE)

ggsave(plot = claim_coverage, filename = "/Users/casey/Documents/censoc/numident_paper/illustrations/claim_coverage.png", height = 11, width = 8.5)
```


```{r}
bunmd_coverage <- coverage %>% 
  filter(numident_file == "bunmd") %>% 
  filter(!name %in% c("weight", "cweight")) %>% 
ggplot() + 
  geom_point(aes(x = reorder(name, value), y = value, shape = all.missing), size = 3, show.legend = FALSE) + 
  geom_segment( aes(x = name, xend = name, y=0, yend=value), color="black") +
  theme_classic() +
  geom_segment(aes(
    x = name,
    xend = name, 
    y = min(value),
    yend = max(value)
  ),
  linetype = "dashed",
  size = 0.1
  ) + # Draw dashed lines
  coord_flip() + 
  scale_shape_manual(values = c(16, 1)) +
  labs(title = "Berkeley Unified Numident Mortality Database (BUNMD) Completeness",
       x = "Variable",
       y = "Completeness %") + 
  ylim(0, 100)


ggsave(plot = bunmd_coverage, filename = "/Users/casey/Documents/censoc/numident_paper/illustrations/bunmd_coverage.png", height = 11, width = 8.5)
```

